LOGIN WITH SYSTEM and oracle password, SID xe


create new user

CREATE USER ibank IDENTIFIED BY Ib4nk_Pass2025;
GRANT CONNECT, RESOURCE TO ibank;
ALTER USER ibank QUOTA UNLIMITED ON USERS;

GRANT ACCESS

GRANT EXECUTE ON DBMS_AQ TO ibank;
GRANT EXECUTE ON SYS.DBMS_AQADM TO ibank;
GRANT EXECUTE ON SYS.DBMS_AQ to IBANK;
GRANT EXECUTE ON SYS.DBMS_AQIN to IBANK;
GRANT EXECUTE ON SYS.DBMS_AQIN to ibank;




  CREATE TABLE "IBANK"."U_CUSTOMER" 
   (	"CUSTOMERID" NUMBER(19,0) NOT NULL ENABLE, 
	"CUSTOMER" VARCHAR2(255 CHAR), 
	"EMAIL" VARCHAR2(255 CHAR), 
	"NAME_E" VARCHAR2(255 CHAR), 
	"PERSONNUM" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("CUSTOMERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;



BEGIN
  FOR i IN 1..50 LOOP
    INSERT INTO IBANK.U_CUSTOMER (
      CUSTOMERID,
      CUSTOMER,
      EMAIL,
      NAME_E,
      PERSONNUM
    )
    VALUES (
      i, -- or use DBMS_RANDOM.VALUE(10000, 99999)
      'CUST_' || DBMS_RANDOM.STRING('U', 6),
      LOWER(DBMS_RANDOM.STRING('A', 6)) || '@example.com',
      INITCAP(DBMS_RANDOM.STRING('A', 5)) || ' ' || INITCAP(DBMS_RANDOM.STRING('A', 7)),
      TO_CHAR(TRUNC(DBMS_RANDOM.VALUE(1000000000, 9999999999)))
    );
  END LOOP;
  COMMIT;
END;
/
