services:
  
  postgresql-master:   
    image: bitnami/postgresql:latest
    container_name: postgresql-master
    ports:
      - '5432'
    volumes:
      - ~/volumes/data/pmatser18/data:/bitnami/postgresql
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf:rw
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=PkAX16o639vwj5u
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=PkAX16o639vwj5u
      - POSTGRESQL_DATABASE=neobank
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - banknet
      
  postgresql-slave:
    image: bitnami/postgresql:latest
    container_name: postgresql-slave
    ports:
      - '5432'
    depends_on:
      - postgresql-master
    volumes:    
      - ~/volumes/data/pslave18/data:/bitnami/postgresql
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf:rw
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=PkAX16o639vwj5u
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_PASSWORD=PkAX16o639vwj5u
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - ALLOW_EMPTY_PASSWORD=yes      
    networks:
      - banknet
  
  pgmanage:
    image: cmdpromptinc/pgmanage-enterprise:latest
    container_name: pgmanage
    ports:
      - "5051:8000"               # host:container
    environment:
      PGMANAGE_LISTEN_PORT: 8000
    volumes:     
      - ~/volumes/data/appdata:/appdata
    stdin_open: true            # equivalent to -it, admin:admin https://hub.docker.com/r/cmdpromptinc/pgmanage-enterprise
    depends_on:
      - postgresql-master
      - postgresql-slave
    links:
      - postgresql-master
      - postgresql-slave
    tty: true
    networks:
      - banknet
    
    
  pgadmin:    
    image: dpage/pgadmin4:9.10.0
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    depends_on:
      - postgresql-master
      - postgresql-slave
    links:
      - postgresql-master
      - postgresql-slave     
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ~/volumes/data/pgbackup/_data/pgadmin:/var/lib/pgadmin
    networks:
      - banknet

networks:
  banknet:
    external: true
